### ISSUE TITLE
[Counter 1] upで値が1上がるクラスを作成する

### ISSUE THREAD

**Issue by ms2sato** [shuma1020/ruby_training#1]
以下のような仕様のCounterクラスを作成しましょう。
counter = Counter.new
counter.up
counter.up
puts counter.value # => 2と表示される

**Comment by shuma1020** [comment]
@ms2sato 
やってみたので確認お願いします！

**Comment by ms2sato** [comment]
```
  def point
    @point
  end

  def point=(value)
    @point = value
  end
```

@shuma1020 

この部分が不要な点を除けばバッチリでは無いでしょうか。これが必要と思って書いたわけでは無い、と理解していいですか？

**Comment by shuma1020** [comment]
@ms2sato 
ゲッターとセッターであると思うのですが、これらは書くものであると認識していました。
